### ISSUE TITLE
how to use CatView like hcat?

### ISSUE THREAD

**Issue by JianghuiDu** [ahwillia/CatViews.jl#15]
It seems `Catview()` behaves like `vcat()`. Is there a way to use it like `hcat()`.

**Comment by andrew-saydjari** [comment]
I had the same question. Why was this closed without answer? Is there some other package that does this?

**Comment by andrew-saydjari** [comment]
Is the correct answer to direct people to MosaicViews.jl?

**Comment by oxinabox** [comment]
CatViews only supports 1D therefore no such thing as `hcat`
